In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pd.options.display.max_columns = None   # 取消最大行列显示
#pd.options.display.max_rows = None

# 导入之前的 女性.csv 数据

In [3]:
df = pd.read_csv(r"C:\Users\EDZ\Desktop\案列\珍爱网各城市小姐姐分析\code\女性.csv")
df.head(2)

,名称,城市,区域,年龄,民族,籍贯,星座,学历,婚姻状况,身高,体重,体型,职业,收入,是否吸烟,是否喝酒,住房情况,车辆情况,子女情况,内心独白,兴趣爱好,择偶条件
0,玉水福兰,北京,朝阳区,33岁,汉族,吉林通化,魔羯座(12.22-01.19),中专,离异,165cm,52kg,富线条美,其他职业,3000元以下,不吸烟,不喝酒,租房,未买车,有孩子且住在一起,88年属龙的，摩羯座，寻找有眼缘的聊得来的他共度余生,喜欢的一道菜：土豆丝|欣赏的一个名人：特斯拉|喜欢做的事：跳拉丁舞|喜欢的一首歌：未填写|喜...,33-40岁|175-195cm|不要吸烟
1,找爱的玫瑰,北京,海淀区,47岁,汉族,河北张家口,魔羯座(12.22-01.19),高中及以下,离异,158cm,55kg,富线条美,其他职业,8001-12000元,不吸烟,不喝酒,和家人同住,已买车,有孩子但不在身边,生活规律，按时睡觉，就是爱美，出的厅堂下得厨房！喜欢厨艺，喜欢跳东方舞！,喜欢的一道菜：酸菜牛肉汤|欣赏的一个名人：马云|喜欢的一首歌：甜蜜蜜|喜欢的一本书：水浒传|...,45-54岁|170-188cm|月薪:1.2万以上|大学本科|不要吸烟|是否想要孩子:以后...

In [4]:
df.shape

(4370, 22)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 22 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
内心独白    4370 non-null object
兴趣爱好    4370 non-null object
择偶条件    4370 non-null object
dtypes: object(22)
memory usage: 751.2+ KB

# 删除 内心独白 兴趣爱好

In [7]:
df.drop(columns = ['内心独白', '兴趣爱好'], inplace=True)

In [8]:
df.head(1)

,名称,城市,区域,年龄,民族,籍贯,星座,学历,婚姻状况,身高,体重,体型,职业,收入,是否吸烟,是否喝酒,住房情况,车辆情况,子女情况,择偶条件
0,玉水福兰,北京,朝阳区,33岁,汉族,吉林通化,魔羯座(12.22-01.19),中专,离异,165cm,52kg,富线条美,其他职业,3000元以下,不吸烟,不喝酒,租房,未买车,有孩子且住在一起,33-40岁|175-195cm|不要吸烟

# 拆分 择偶条件

## 新增 年龄要求  
位置在子女情况前面

In [13]:
a = df.择偶条件.str.split('|')
a

0                               [33-40岁, 175-195cm, 不要吸烟]
1       [45-54岁, 170-188cm, 月薪:1.2万以上, 大学本科, 不要吸烟, 是否想...
2                        [31-45岁, 工作地:北京朝阳区, 月薪:8千以上, 未婚]
3       [46-53岁, 170-180cm, 工作地:北京朝阳区, 月薪:8千以上, 离异, 体型...
4                                       [39-54岁, 月薪:5千以上]
                              ...
4365    [40-47岁, 170-178cm, 工作地:广东珠海, 月薪:2万以上, 体型:一般, ...
4366                         [31-45岁, 172-182cm, 月薪:2万以上]
4367                 [33-43岁, 170-180cm, 工作地:广东珠海香洲区, 未婚]
4368    [29-35岁, 170-185cm, 工作地:广东珠海, 月薪:1.2万以上, 大学本科,...
4369                   [49-63岁, 工作地:广东珠海香洲区, 月薪:5万以上, 未婚]
Name: 择偶条件, Length: 4370, dtype: object

In [15]:
df.insert(19, '年龄要求', '不明')

In [17]:
def x(s):
    for i in s:
        if '岁' in i:
            return i

In [18]:
a.map(x)

0       33-40岁
1       45-54岁
2       31-45岁
3       46-53岁
4       39-54岁
         ...
4365    40-47岁
4366    31-45岁
4367    33-43岁
4368    29-35岁
4369    49-63岁
Name: 择偶条件, Length: 4370, dtype: object

In [19]:
df['年龄要求'] = a.map(x)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 21 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4307 non-null object
择偶条件    4370 non-null object
dtypes: object(21)
memory usage: 717.1+ KB

In [24]:
# 提取出 年龄要求有缺失的行
df[df.年龄要求.isna()]    # 那我们以 不明 填写

,名称,城市,区域,年龄,民族,籍贯,星座,学历,婚姻状况,身高,体重,体型,职业,收入,是否吸烟,是否喝酒,住房情况,车辆情况,子女情况,年龄要求,择偶条件
107,Mia啦啦啦,北京,海淀区,27岁,汉族,黑龙江大庆,天秤座(09.23-10.22),大学本科,未婚,164cm,45kg,瘦长,医疗管理,12001-20000元,不明,稍微喝一点酒,打算婚后购房,不明,没有小孩,None,工作地:北京|未婚
136,米谷,上海,长宁区,39岁,汉族,海南三亚,天秤座(09.23-10.22),大学本科,未婚,166cm,52kg,丰满,外贸经理,3000元以下,不明,社交场合会喝酒,已购房,已买车,没有小孩,None,工作地:上海长宁区|未婚|不要吸烟
170,格调,上海,闵行区,42岁,汉族,不明,魔羯座(12.22-01.19),中专,离异,160cm,不明,不明,中专,3001-5000元,不明,不明,不明,不明,不明,None,工作地:安徽淮南田家庵区|月薪:5千以上
326,Sherry,广州,番禺区,23岁,汉族,广东广州,魔羯座(12.22-01.19),大专,未婚,158cm,40kg,保密,外贸专员,8001-12000元,不吸烟,不喝酒,打算婚后购房,未买车,没有小孩,None,170cm以上|未婚|体型:一般|没有小孩
429,清沐宸汐,深圳,龙岗区,23岁,汉族,不明,射手座(11.22-12.21),大专,未婚,150cm,不明,不明,其他职业,5001-8000元,不吸烟,不明,不明,不明,没有小孩,None,170-175cm|工作地:广东深圳龙岗区|月薪:8千以下|大专|未婚|不要吸烟|没有小孩
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4156,依娜,中山,东区街道,38岁,汉族,湖南益阳,魔羯座(12.22-01.19),中专,离异,165cm,51kg,苗条,销售,3001-5000元,不吸烟,不喝酒,租房,未买车,有孩子且住在一起,None,167-199cm|工作地:广东中山石岐街道|月薪:2万-5万
4172,丽Li,中山,东区街道,34岁,汉族,广东湛江,射手座(11.22-12.21),大专,离异,160cm,55kg,富线条美,服务业,5001-8000元,不吸烟,不喝酒,租房,已买车,有孩子且偶尔会一起住,None,170-179cm|工作地:广东中山东区街道|体型:壮实|是否想要孩子:不想要孩子
4278,喵喵,珠海,香洲区,32岁,汉族,广东珠海,天蝎座(10.23-11.21),大专,未婚,159cm,45kg,苗条,设计师,8001-12000元,不吸烟,社交场合会喝酒,租房,未买车,没有小孩,None,170-190cm|月薪:1.2万以上
4295,开心每一天,珠海,香洲区,44岁,汉族,广东珠海,魔羯座(12.22-01.19),大专,离异,155cm,不明,一般,大专,8001-12000元,不吸烟,社交场合会喝酒,已购房,已买车,有孩子且住在一起,None,170-175cm|工作地:广东珠海香洲区|月薪:1.2万以上|大专|离异|不要吸烟|是否想...
4328,相遇并非偶然,珠海,香洲区,33岁,汉族,广东湛江,魔羯座(12.22-01.19),中专,离异,165cm,48kg,瘦长,中专,12001-20000元,不吸烟,不喝酒,不明,不明,有孩子且偶尔会一起住,None,173cm以上|工作地:广东珠海|不要吸烟

In [26]:
df.年龄要求.fillna('不明', inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 21 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4370 non-null object
择偶条件    4370 non-null object
dtypes: object(21)
memory usage: 717.1+ KB

In [31]:
set(df.年龄要求.value_counts().index)  # 无异常值

{'18-18岁',
 '18-23岁',
 '18-25岁',
 '18-26岁',
 '18-27岁',
 '18-28岁',
 '18-29岁',
 '18-30岁',
 '18-31岁',
 '18-32岁',
 '18-33岁',
 '18-40岁',
 '19-20岁',
 '19-26岁',
 '19-30岁',
 '19-31岁',
 '19-33岁',
 '19-34岁',
 '19-36岁',
 '20-21岁',
 '20-24岁',
 '20-27岁',
 '20-28岁',
 '20-30岁',
 '20-31岁',
 '20-33岁',
 '20-34岁',
 '20-35岁',
 '20-36岁',
 '20-40岁',
 '21-25岁',
 '21-28岁',
 '21-30岁',
 '21-31岁',
 '21-33岁',
 '21-35岁',
 '21-36岁',
 '22-25岁',
 '22-26岁',
 '22-27岁',
 '22-28岁',
 '22-30岁',
 '22-31岁',
 '22-32岁',
 '22-33岁',
 '22-34岁',
 '22-35岁',
 '22-36岁',
 '22-37岁',
 '22-38岁',
 '22-39岁',
 '22-40岁',
 '22-43岁',
 '22-45岁',
 '22岁以上',
 '23-26岁',
 '23-27岁',
 '23-28岁',
 '23-29岁',
 '23-30岁',
 '23-31岁',
 '23-32岁',
 '23-33岁',
 '23-34岁',
 '23-35岁',
 '23-36岁',
 '23-37岁',
 '23-38岁',
 '23-40岁',
 '23-55岁',
 '23岁以上',
 '24-25岁',
 '24-26岁',
 '24-27岁',
 '24-28岁',
 '24-29岁',
 '24-30岁',
 '24-31岁',
 '24-32岁',
 '24-33岁',
 '24-34岁',
 '24-35岁',
 '24-36岁',
 '24-38岁',
 '24-39岁',
 '24-40岁',
 '24岁以上',
 '25-27岁',
 '25-29岁',
 '25-30岁',
 '25-31岁',
 '25-32岁',
 '25-33岁',
 '25-34岁',
 '25-35岁',
 '25-36岁',
 '25-37岁',
 '25-38岁',
 '25-39岁',
 '25-40岁',
 '25-41岁',
 '25-42岁',
 '25-43岁',
 '25-44岁',
 '25-45岁',
 '25岁以上',
 '26-28岁',
 '26-29岁',
 '26-30岁',
 '26-31岁',
 '26-32岁',
 '26-33岁',
 '26-34岁',
 '26-35岁',
 '26-36岁',
 '26-37岁',
 '26-38岁',
 '26-39岁',
 '26-40岁',
 '26-41岁',
 '26-42岁',
 '26-45岁',
 '26-48岁',
 '26-55岁',
 '26岁以上',
 '26岁以下',
 '27-29岁',
 '27-30岁',
 '27-31岁',
 '27-32岁',
 '27-33岁',
 '27-34岁',
 '27-35岁',
 '27-36岁',
 '27-37岁',
 '27-38岁',
 '27-39岁',
 '27-40岁',
 '27-41岁',
 '27-42岁',
 '27-45岁',
 '27-58岁',
 '27岁以上',
 '28-28岁',
 '28-29岁',
 '28-30岁',
 '28-31岁',
 '28-32岁',
 '28-33岁',
 '28-34岁',
 '28-35岁',
 '28-36岁',
 '28-37岁',
 '28-38岁',
 '28-39岁',
 '28-40岁',
 '28-41岁',
 '28-42岁',
 '28-43岁',
 '28-44岁',
 '28-45岁',
 '28-46岁',
 '28-47岁',
 '28-48岁',
 '28-50岁',
 '28岁以上',
 '28岁以下',
 '29-31岁',
 '29-32岁',
 '29-33岁',
 '29-34岁',
 '29-35岁',
 '29-36岁',
 '29-37岁',
 '29-38岁',
 '29-39岁',
 '29-40岁',
 '29-41岁',
 '29-42岁',
 '29-43岁',
 '29-44岁',
 '29-45岁',
 '29-50岁',
 '29-55岁',
 '29岁以上',
 '29岁以下',
 '30-32岁',
 '30-34岁',
 '30-35岁',
 '30-36岁',
 '30-37岁',
 '30-38岁',
 '30-39岁',
 '30-40岁',
 '30-41岁',
 '30-42岁',
 '30-43岁',
 '30-44岁',
 '30-45岁',
 '30-46岁',
 '30-47岁',
 '30-48岁',
 '30-50岁',
 '30-55岁',
 '30-60岁',
 '30岁以上',
 '31-34岁',
 '31-35岁',
 '31-36岁',
 '31-37岁',
 '31-38岁',
 '31-39岁',
 '31-40岁',
 '31-41岁',
 '31-42岁',
 '31-43岁',
 '31-45岁',
 '31-46岁',
 '31-48岁',
 '31-50岁',
 '31岁以上',
 '31岁以下',
 '32-32岁',
 '32-33岁',
 '32-34岁',
 '32-35岁',
 '32-36岁',
 '32-37岁',
 '32-38岁',
 '32-39岁',
 '32-40岁',
 '32-41岁',
 '32-42岁',
 '32-43岁',
 '32-44岁',
 '32-45岁',
 '32-46岁',
 '32-48岁',
 '32-58岁',
 '32岁以上',
 '32岁以下',
 '33-35岁',
 '33-36岁',
 '33-37岁',
 '33-38岁',
 '33-39岁',
 '33-40岁',
 '33-41岁',
 '33-42岁',
 '33-43岁',
 '33-44岁',
 '33-45岁',
 '33-46岁',
 '33-47岁',
 '33-48岁',
 '33-49岁',
 '33-50岁',
 '33-55岁',
 '33岁以上',
 '33岁以下',
 '34-36岁',
 '34-37岁',
 '34-38岁',
 '34-39岁',
 '34-40岁',
 '34-42岁',
 '34-43岁',
 '34-44岁',
 '34-45岁',
 '34-46岁',
 '34-47岁',
 '34-48岁',
 '34-49岁',
 '34-55岁',
 '34-59岁',
 '34-99岁',
 '34岁以上',
 '35-35岁',
 '35-37岁',
 '35-38岁',
 '35-39岁',
 '35-40岁',
 '35-41岁',
 '35-42岁',
 '35-43岁',
 '35-44岁',
 '35-45岁',
 '35-46岁',
 '35-47岁',
 '35-48岁',
 '35-49岁',
 '35-50岁',
 '35-52岁',
 '35-55岁',
 '35-60岁',
 '35岁以上',
 '35岁以下',
 '36-38岁',
 '36-39岁',
 '36-40岁',
 '36-41岁',
 '36-42岁',
 '36-43岁',
 '36-44岁',
 '36-45岁',
 '36-46岁',
 '36-47岁',
 '36-48岁',
 '36-49岁',
 '36-50岁',
 '36-51岁',
 '36-52岁',
 '36-53岁',
 '36-55岁',
 '36-60岁',
 '36岁以上',
 '36岁以下',
 '37-37岁',
 '37-41岁',
 '37-42岁',
 '37-43岁',
 '37-44岁',
 '37-45岁',
 '37-46岁',
 '37-47岁',
 '37-48岁',
 '37-50岁',
 '37-51岁',
 '37-52岁',
 '37-62岁',
 '37岁以上',
 '38-38岁',
 '38-40岁',
 '38-41岁',
 '38-42岁',
 '38-43岁',
 '38-44岁',
 '38-45岁',
 '38-46岁',
 '38-47岁',
 '38-48岁',
 '38-49岁',
 '38-50岁',
 '38-52岁',
 '38-53岁',
 '38-55岁',
 '38-58岁',
 '38岁以上',
 '39-42岁',
 '39-43岁',
 '39-44岁',
 '39-45岁',
 '39-46岁',
 '39-47岁',
 '39-48岁',
 '39-49岁',
 '39-50岁',
 '39-51岁',
 '39-52岁',
 '39-53岁',
 '39-54岁',
 '39-55岁',
 '39岁以上',
 '40-41岁',
 '40-42岁',
 '40-43岁',
 '40-44岁',
 '40-45岁',
 '40-46岁',
 '40-47岁',
 '40-48岁',
 '40-49岁',
 '40-50岁',
 '40-51岁',
 '40-52岁',
 '40-53岁',
 '40-54岁',
 '40-55岁',
 '40-56岁',
 '40-57岁',
 '40-58岁',
 '40-60岁',
 '40-61岁',
 '40-68岁',
 '40-99岁',
 '40岁以上',
 '40岁以下',
 '41-41岁',
 '41-42岁',
 '41-44岁',
 '41-46岁',
 '41-48岁',
 '41-49岁',
 '41-50岁',
 '41-51岁',
 '41-52岁',
 '41-53岁',
 '41-54岁',
 '41-55岁',
 '41-56岁',
 '41-57岁',
 '41岁以上',
 '42-43岁',
 '42-44岁',
 '42-45岁',
 '42-47岁',
 '42-48岁',
 '42-49岁',
 '42-50岁',
 '42-51岁',
 '42-52岁',
 '42-53岁',
 '42-54岁',
 '42-55岁',
 '42-56岁',
 '42-58岁',
 '42-70岁',
 '42岁以上',
 '42岁以下',
 '43-45岁',
 '43-46岁',
 '43-47岁',
 '43-48岁',
 '43-49岁',
 '43-50岁',
 '43-51岁',
 '43-52岁',
 '43-53岁',
 '43-55岁',
 '43-56岁',
 '43-57岁',
 '43-58岁',
 '43-59岁',
 '43-60岁',
 '43-79岁',
 '43岁以上',
 '44-44岁',
 '44-48岁',
 '44-49岁',
 '44-50岁',
 '44-51岁',
 '44-52岁',
 '44-53岁',
 '44-54岁',
 '44-55岁',
 '44-56岁',
 '44-57岁',
 '44-58岁',
 '44-60岁',
 '44-63岁',
 '44岁以上',
 '45-45岁',
 '45-48岁',
 '45-49岁',
 '45-50岁',
 '45-51岁',
 '45-52岁',
 '45-53岁',
 '45-54岁',
 '45-55岁',
 '45-56岁',
 '45-57岁',
 '45-58岁',
 '45-59岁',
 '45-60岁',
 '45-61岁',
 '45-65岁',
 '45岁以上',
 '45岁以下',
 '46-50岁',
 '46-51岁',
 '46-52岁',
 '46-53岁',
 '46-54岁',
 '46-55岁',
 '46-56岁',
 '46-57岁',
 '46-58岁',
 '46-59岁',
 '46-60岁',
 '46-61岁',
 '46-62岁',
 '46岁以上',
 '46岁以下',
 '47-50岁',
 '47-51岁',
 '47-52岁',
 '47-53岁',
 '47-54岁',
 '47-55岁',
 '47-56岁',
 '47-57岁',
 '47-58岁',
 '47-59岁',
 '47-60岁',
 '47-61岁',
 '47-63岁',
 '47-64岁',
 '47-65岁',
 '47岁以上',
 '48-48岁',
 '48-49岁',
 '48-52岁',
 '48-53岁',
 '48-54岁',
 '48-55岁',
 '48-56岁',
 '48-57岁',
 '48-58岁',
 '48-59岁',
 '48-60岁',
 '48-61岁',
 '48-62岁',
 '48-65岁',
 '48岁以上',
 '49-50岁',
 '49-53岁',
 '49-54岁',
 '49-55岁',
 '49-56岁',
 '49-57岁',
 '49-58岁',
 '49-59岁',
 '49-60岁',
 '49-62岁',
 '49-63岁',
 '49-65岁',
 '49岁以上',
 '49岁以下',
 '50-52岁',
 '50-55岁',
 '50-56岁',
 '50-57岁',
 '50-58岁',
 '50-59岁',
 '50-60岁',
 '50-62岁',
 '50-64岁',
 '50-65岁',
 '50-68岁',
 '50岁以上',
 '50岁以下',
 '51-52岁',
 '51-53岁',
 '51-55岁',
 '51-56岁',
 '51-57岁',
 '51-58岁',
 '51-59岁',
 '51-60岁',
 '51-61岁',
 '51-65岁',
 '51岁以上',
 '52-55岁',
 '52-56岁',
 '52-57岁',
 '52-58岁',
 '52-59岁',
 '52-60岁',
 '52-62岁',
 '52-63岁',
 '52-65岁',
 '52-66岁',
 '52岁以上',
 '53-56岁',
 '53-57岁',
 '53-58岁',
 '53-59岁',
 '53-60岁',
 '53-62岁',
 '53-63岁',
 '53-65岁',
 '53-66岁',
 '53-67岁',
 '53-68岁',
 '53岁以上',
 '53岁以下',
 '54-55岁',
 '54-58岁',
 '54-59岁',
 '54-60岁',
 '54-62岁',
 '54-63岁',
 '54-64岁',
 '54-65岁',
 '54-68岁',
 '54-69岁',
 '54-70岁',
 '54-72岁',
 '54岁以上',
 '55-55岁',
 '55-57岁',
 '55-60岁',
 '55-61岁',
 '55-62岁',
 '55-63岁',
 '55-64岁',
 '55-65岁',
 '55-68岁',
 '55-69岁',
 '55-70岁',
 '55岁以上',
 '55岁以下',
 '56-56岁',
 '56-60岁',
 '56-61岁',
 '56-62岁',
 '56-63岁',
 '56-64岁',
 '56-65岁',
 '56-70岁',
 '56-72岁',
 '56岁以上',
 '56岁以下',
 '57-59岁',
 '57-60岁',
 '57-62岁',
 '57-65岁',
 '57-67岁',
 '57-68岁',
 '57-71岁',
 '57岁以上',
 '57岁以下',
 '58-60岁',
 '58-62岁',
 '58-63岁',
 '58-64岁',
 '58-65岁',
 '58-66岁',
 '58-68岁',
 '58-70岁',
 '58岁以上',
 '58岁以下',
 '59-63岁',
 '59-65岁',
 '59-66岁',
 '59-68岁',
 '59-73岁',
 '59-75岁',
 '60-61岁',
 '60-62岁',
 '60-63岁',
 '60-65岁',
 '60-66岁',
 '60-68岁',
 '60-70岁',
 '60岁以上',
 '60岁以下',
 '61-70岁',
 '61-75岁',
 '62-65岁',
 '62-67岁',
 '62-68岁',
 '62岁以上',
 '62岁以下',
 '63-72岁',
 '63-76岁',
 '63-77岁',
 '63岁以上',
 '63岁以下',
 '64-65岁',
 '64-67岁',
 '64-71岁',
 '65-70岁',
 '65-73岁',
 '65-74岁',
 '65-80岁',
 '65岁以下',
 '66-70岁',
 '66-72岁',
 '66-73岁',
 '66-80岁',
 '66岁以上',
 '66岁以下',
 '67-72岁',
 '68-72岁',
 '68-76岁',
 '68岁以下',
 '69-83岁',
 '70-80岁',
 '71-83岁',
 '72岁以下',
 '73-75岁',
 '74-79岁',
 '76-98岁',
 '不明'}

## 新增 身高 要求  
位置放在 年龄要求 后面

In [38]:
a = df.择偶条件.str.split('|')
a

0                               [33-40岁, 175-195cm, 不要吸烟]
1       [45-54岁, 170-188cm, 月薪:1.2万以上, 大学本科, 不要吸烟, 是否想...
2                        [31-45岁, 工作地:北京朝阳区, 月薪:8千以上, 未婚]
3       [46-53岁, 170-180cm, 工作地:北京朝阳区, 月薪:8千以上, 离异, 体型...
4                                       [39-54岁, 月薪:5千以上]
                              ...
4365    [40-47岁, 170-178cm, 工作地:广东珠海, 月薪:2万以上, 体型:一般, ...
4366                         [31-45岁, 172-182cm, 月薪:2万以上]
4367                 [33-43岁, 170-180cm, 工作地:广东珠海香洲区, 未婚]
4368    [29-35岁, 170-185cm, 工作地:广东珠海, 月薪:1.2万以上, 大学本科,...
4369                   [49-63岁, 工作地:广东珠海香洲区, 月薪:5万以上, 未婚]
Name: 择偶条件, Length: 4370, dtype: object

In [40]:
df.insert(20, '身高要求', '不明')

In [41]:
def x(s):
    for i in s:
        if 'cm' in i:
            return i

In [42]:
a.map(x)

0       175-195cm
1       170-188cm
2            None
3       170-180cm
4            None
          ...
4365    170-178cm
4366    172-182cm
4367    170-180cm
4368    170-185cm
4369         None
Name: 择偶条件, Length: 4370, dtype: object

In [44]:
df['身高要求'] = a.map(x)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 22 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4370 non-null object
身高要求    3090 non-null object
择偶条件    4370 non-null object
dtypes: object(22)
memory usage: 751.2+ KB

In [49]:
# 提取出身高要求有缺失的行
df[df.身高要求.isna()]  # 填充不明

,名称,城市,区域,年龄,民族,籍贯,星座,学历,婚姻状况,身高,体重,体型,职业,收入,是否吸烟,是否喝酒,住房情况,车辆情况,子女情况,年龄要求,身高要求,择偶条件
2,芯儿,北京,朝阳区,36岁,汉族,河北保定,天蝎座(10.23-11.21),大学本科,未婚,160cm,45kg,苗条,传媒/艺术,5001-8000元,不吸烟,稍微喝一点酒,租房,未买车,没有小孩,31-45岁,None,31-45岁|工作地:北京朝阳区|月薪:8千以上|未婚
4,冰心,北京,石景山区,48岁,汉族,黑龙江牡丹江,射手座(11.22-12.21),高中及以下,离异,160cm,不明,不明,高中及以下,3001-5000元,不吸烟,不喝酒,和家人同住,未买车,有孩子但不在身边,39-54岁,None,39-54岁|月薪:5千以上
8,五七,北京,海淀区,25岁,汉族,江苏徐州,魔羯座(12.22-01.19),大学本科,未婚,165cm,不明,不明,大学本科,8001-12000元,不吸烟,不喝酒,不明,不明,不明,20-34岁,None,20-34岁|工作地:安徽合肥蜀山区|月薪:1.2万以上|未婚
9,六六,北京,石景山区,51岁,汉族,吉林吉林,魔羯座(12.22-01.19),中专,离异,160cm,58kg,不明,销售总监,5001-8000元,不吸烟,不喝酒,租房,未买车,有孩子但不在身边,53-63岁,None,53-63岁|工作地:北京石景山区|月薪:8千以上
14,卓越,北京,东城区,34岁,汉族,河北张家口,魔羯座(12.22-01.19),硕士,离异,170cm,55kg,高大美丽,高级管理,12001-20000元,不吸烟,不喝酒,已购房,已买车,有孩子且住在一起,30-47岁,None,30-47岁
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4357,天使的眼泪,珠海,金湾区,32岁,汉族,湖南娄底,魔羯座(12.22-01.19),大专,离异,160cm,49kg,不明,业务跟单,5001-8000元,不吸烟,不喝酒,租房,未买车,没有小孩,28-42岁,None,28-42岁|工作地:广东珠海金湾区|月薪:8千以上
4358,菁菁,珠海,香洲区,35岁,汉族,不明,魔羯座(12.22-01.19),中专,离异,156cm,45kg,苗条,中专,5001-8000元,不吸烟,稍微喝一点酒,不明,不明,不明,30-44岁,None,30-44岁|工作地:广东|月薪:8千以上
4363,逗逗,珠海,香洲区,30岁,汉族,湖北孝感,射手座(11.22-12.21),大学本科,未婚,160cm,不明,不明,大学本科,12001-20000元,不吸烟,不喝酒,租房,未买车,没有小孩,26-40岁,None,26-40岁|工作地:广东珠海香洲区|月薪:2万以上|未婚
4364,澜纸清兰,珠海,金湾区,43岁,汉族,广东珠海,魔羯座(12.22-01.19),高中及以下,离异,157cm,不明,不明,高中及以下,3000元以下,不吸烟,不喝酒,租房,不明,没有小孩,39-53岁,None,39-53岁|工作地:广东珠海金湾区|月薪:3千以上
4369,Mask,珠海,香洲区,54岁,汉族,北京,魔羯座(12.22-01.19),大专,未婚,165cm,52kg,保密,其他职业,20001-50000元,不明,稍微喝一点酒,已购房,已买车,没有小孩,49-63岁,None,49-63岁|工作地:广东珠海香洲区|月薪:5万以上|未婚

In [51]:
df.身高要求.fillna('不明', inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 22 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4370 non-null object
身高要求    4370 non-null object
择偶条件    4370 non-null object
dtypes: object(22)
memory usage: 751.2+ KB

In [56]:
set(df.身高要求.value_counts().index)

{'129-180cm',
 '130-210cm',
 '133-172cm',
 '140cm以上',
 '145-160cm',
 '146cm以上',
 '150-158cm',
 '150-160cm',
 '150-161cm',
 '150-165cm',
 '150cm以上',
 '151-164cm',
 '151-167cm',
 '152-165cm',
 '153-164cm',
 '155-163cm',
 '155-165cm',
 '155-166cm',
 '155-168cm',
 '155-170cm',
 '155-175cm',
 '155-186cm',
 '155-189cm',
 '155-200cm',
 '155cm以上',
 '156-165cm',
 '156-170cm',
 '156-181cm',
 '156cm以上',
 '157-172cm',
 '157-178cm',
 '158-165cm',
 '158-168cm',
 '158-170cm',
 '158-173cm',
 '158-175cm',
 '158cm以上',
 '160-160cm',
 '160-164cm',
 '160-165cm',
 '160-168cm',
 '160-169cm',
 '160-170cm',
 '160-173cm',
 '160-174cm',
 '160-175cm',
 '160-178cm',
 '160-180cm',
 '160-183cm',
 '160-185cm',
 '160-187cm',
 '160-190cm',
 '160cm以上',
 '160cm以下',
 '161-180cm',
 '161-190cm',
 '161cm以上',
 '162-168cm',
 '162-175cm',
 '162-180cm',
 '162-181cm',
 '164-172cm',
 '164cm以上',
 '165-170cm',
 '165-172cm',
 '165-175cm',
 '165-176cm',
 '165-177cm',
 '165-178cm',
 '165-179cm',
 '165-180cm',
 '165-181cm',
 '165-185cm',
 '165-190cm',
 '165cm以上',
 '165cm以下',
 '166-170cm',
 '166-172cm',
 '166-173cm',
 '166-175cm',
 '166-176cm',
 '166-177cm',
 '166-178cm',
 '166-179cm',
 '166-180cm',
 '166-185cm',
 '166-190cm',
 '166cm以上',
 '166cm以下',
 '167-172cm',
 '167-175cm',
 '167-176cm',
 '167-180cm',
 '167-181cm',
 '167-199cm',
 '167cm以上',
 '168-168cm',
 '168-169cm',
 '168-170cm',
 '168-171cm',
 '168-172cm',
 '168-173cm',
 '168-174cm',
 '168-175cm',
 '168-176cm',
 '168-178cm',
 '168-180cm',
 '168-182cm',
 '168-183cm',
 '168-184cm',
 '168-185cm',
 '168-186cm',
 '168-188cm',
 '168-189cm',
 '168-190cm',
 '168-211cm',
 '168cm以上',
 '168cm以下',
 '169-169cm',
 '169-170cm',
 '169-173cm',
 '169-175cm',
 '169-177cm',
 '169-178cm',
 '169-180cm',
 '169-182cm',
 '169-186cm',
 '169cm以上',
 '170-170cm',
 '170-171cm',
 '170-173cm',
 '170-174cm',
 '170-175cm',
 '170-176cm',
 '170-177cm',
 '170-178cm',
 '170-179cm',
 '170-180cm',
 '170-181cm',
 '170-182cm',
 '170-183cm',
 '170-184cm',
 '170-185cm',
 '170-186cm',
 '170-187cm',
 '170-188cm',
 '170-189cm',
 '170-190cm',
 '170-194cm',
 '170-195cm',
 '170-200cm',
 '170-206cm',
 '170-211cm',
 '170cm以上',
 '170cm以下',
 '171-173cm',
 '171-175cm',
 '171-177cm',
 '171-178cm',
 '171-179cm',
 '171-180cm',
 '171-181cm',
 '171-182cm',
 '171-185cm',
 '171-188cm',
 '171-211cm',
 '171cm以上',
 '172-172cm',
 '172-173cm',
 '172-175cm',
 '172-176cm',
 '172-177cm',
 '172-178cm',
 '172-179cm',
 '172-180cm',
 '172-181cm',
 '172-182cm',
 '172-183cm',
 '172-185cm',
 '172-186cm',
 '172-187cm',
 '172-188cm',
 '172-189cm',
 '172-190cm',
 '172-196cm',
 '172-210cm',
 '172cm以上',
 '172cm以下',
 '173-173cm',
 '173-175cm',
 '173-176cm',
 '173-177cm',
 '173-178cm',
 '173-179cm',
 '173-180cm',
 '173-181cm',
 '173-182cm',
 '173-183cm',
 '173-184cm',
 '173-185cm',
 '173-186cm',
 '173-187cm',
 '173-188cm',
 '173-189cm',
 '173-190cm',
 '173-193cm',
 '173-195cm',
 '173-203cm',
 '173cm以上',
 '173cm以下',
 '174-177cm',
 '174-178cm',
 '174-179cm',
 '174-180cm',
 '174-181cm',
 '174-182cm',
 '174-183cm',
 '174-184cm',
 '174-185cm',
 '174-188cm',
 '174-189cm',
 '174-211cm',
 '174cm以上',
 '175-175cm',
 '175-176cm',
 '175-177cm',
 '175-178cm',
 '175-179cm',
 '175-180cm',
 '175-181cm',
 '175-182cm',
 '175-183cm',
 '175-184cm',
 '175-185cm',
 '175-186cm',
 '175-187cm',
 '175-188cm',
 '175-189cm',
 '175-190cm',
 '175-192cm',
 '175-193cm',
 '175-195cm',
 '175-196cm',
 '175-198cm',
 '175-199cm',
 '175-211cm',
 '175cm以上',
 '175cm以下',
 '176-176cm',
 '176-178cm',
 '176-180cm',
 '176-181cm',
 '176-182cm',
 '176-183cm',
 '176-185cm',
 '176-186cm',
 '176-188cm',
 '176-189cm',
 '176-190cm',
 '176-196cm',
 '176cm以上',
 '176cm以下',
 '177-177cm',
 '177-182cm',
 '177-183cm',
 '177-184cm',
 '177-185cm',
 '177-187cm',
 '177-188cm',
 '177-189cm',
 '177-190cm',
 '177cm以上',
 '177cm以下',
 '178-178cm',
 '178-180cm',
 '178-181cm',
 '178-182cm',
 '178-183cm',
 '178-185cm',
 '178-186cm',
 '178-187cm',
 '178-188cm',
 '178-189cm',
 '178-190cm',
 '178-195cm',
 '178-210cm',
 '178cm以上',
 '178cm以下',
 '179-183cm',
 '179-185cm',
 '179-189cm',
 '179-190cm',
 '179-192cm',
 '179cm以上',
 '179cm以下',
 '180-180cm',
 '180-182cm',
 '180-183cm',
 '180-185cm',
 '180-186cm',
 '180-189cm',
 '180-190cm',
 '180-191cm',
 '180-192cm',
 '180-195cm',
 '180cm以上',
 '180cm以下',
 '181-187cm',
 '181-188cm',
 '181cm以上',
 '181cm以下',
 '182-195cm',
 '182cm以上',
 '183cm以上',
 '185-187cm',
 '185cm以上',
 '185cm以下',
 '188cm以下',
 '202-208cm',
 '不明'}

## 新增 收入要求  
位置放在 身高要求 后面

In [59]:
a = df.择偶条件.str.split('|')
a

0                               [33-40岁, 175-195cm, 不要吸烟]
1       [45-54岁, 170-188cm, 月薪:1.2万以上, 大学本科, 不要吸烟, 是否想...
2                        [31-45岁, 工作地:北京朝阳区, 月薪:8千以上, 未婚]
3       [46-53岁, 170-180cm, 工作地:北京朝阳区, 月薪:8千以上, 离异, 体型...
4                                       [39-54岁, 月薪:5千以上]
                              ...
4365    [40-47岁, 170-178cm, 工作地:广东珠海, 月薪:2万以上, 体型:一般, ...
4366                         [31-45岁, 172-182cm, 月薪:2万以上]
4367                 [33-43岁, 170-180cm, 工作地:广东珠海香洲区, 未婚]
4368    [29-35岁, 170-185cm, 工作地:广东珠海, 月薪:1.2万以上, 大学本科,...
4369                   [49-63岁, 工作地:广东珠海香洲区, 月薪:5万以上, 未婚]
Name: 择偶条件, Length: 4370, dtype: object

In [63]:
df.insert(21, '收入要求', '不明')

In [64]:
def x(s):
    for i in s:
        if '月薪' in i:
            return i

In [65]:
a.map(x)

0            None
1       月薪:1.2万以上
2         月薪:8千以上
3         月薪:8千以上
4         月薪:5千以上
          ...
4365      月薪:2万以上
4366      月薪:2万以上
4367         None
4368    月薪:1.2万以上
4369      月薪:5万以上
Name: 择偶条件, Length: 4370, dtype: object

In [67]:
df['收入要求'] = a.map(x)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 23 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4370 non-null object
身高要求    4370 non-null object
收入要求    3889 non-null object
择偶条件    4370 non-null object
dtypes: object(23)
memory usage: 785.4+ KB

In [69]:
df.收入要求.fillna('不明', inplace=True)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4370 entries, 0 to 4369
Data columns (total 23 columns):
名称      4370 non-null object
城市      4370 non-null object
区域      4370 non-null object
年龄      4370 non-null object
民族      4370 non-null object
籍贯      4370 non-null object
星座      4370 non-null object
学历      4370 non-null object
婚姻状况    4370 non-null object
身高      4370 non-null object
体重      4370 non-null object
体型      4370 non-null object
职业      4370 non-null object
收入      4370 non-null object
是否吸烟    4370 non-null object
是否喝酒    4370 non-null object
住房情况    4370 non-null object
车辆情况    4370 non-null object
子女情况    4370 non-null object
年龄要求    4370 non-null object
身高要求    4370 non-null object
收入要求    4370 non-null object
择偶条件    4370 non-null object
dtypes: object(23)
memory usage: 785.4+ KB

In [72]:
df.收入要求.value_counts()

月薪:8千以上       875
月薪:5千以上       767
月薪:1.2万以上     670
月薪:2万以上       502
不明            481
月薪:3千以上       237
月薪:5万以上       146
月薪:2万-5万      114
月薪:1.2万-2万    112
月薪:8千-1.2万     78
月薪:8千-2万       77
月薪:1.2万-5万     59
月薪:5千-8千       57
月薪:5千-1.2万     47
月薪:8千-5万       36
月薪:5千-2万       26
月薪:3千-5千       23
月薪:5千-5万       19
月薪:2万以下         7
月薪:3千-8千        6
月薪:3千-1.2万      5
月薪:3千以下         5
月薪:8千以下         4
月薪:1.2万以下       4
月薪:5千以下         4
月薪:3千-5万        3
月薪:3千-3千        2
月薪:5万以下         2
月薪:3千-2万        1
月薪:2万-2万        1
Name: 收入要求, dtype: int64

In [75]:
def x(s):
    if '月薪' in s:
        return s.replace('月薪:', '')
    else:
        return s

In [76]:
df.收入要求.map(x)

0           不明
1       1.2万以上
2         8千以上
3         8千以上
4         5千以上
         ...
4365      2万以上
4366      2万以上
4367        不明
4368    1.2万以上
4369      5万以上
Name: 收入要求, Length: 4370, dtype: object

In [78]:
df['收入要求'] = df.收入要求.map(x)

In [79]:
df

,名称,城市,区域,年龄,民族,籍贯,星座,学历,婚姻状况,身高,体重,体型,职业,收入,是否吸烟,是否喝酒,住房情况,车辆情况,子女情况,年龄要求,身高要求,收入要求,择偶条件
0,玉水福兰,北京,朝阳区,33岁,汉族,吉林通化,魔羯座(12.22-01.19),中专,离异,165cm,52kg,富线条美,其他职业,3000元以下,不吸烟,不喝酒,租房,未买车,有孩子且住在一起,33-40岁,175-195cm,不明,33-40岁|175-195cm|不要吸烟
1,找爱的玫瑰,北京,海淀区,47岁,汉族,河北张家口,魔羯座(12.22-01.19),高中及以下,离异,158cm,55kg,富线条美,其他职业,8001-12000元,不吸烟,不喝酒,和家人同住,已买车,有孩子但不在身边,45-54岁,170-188cm,1.2万以上,45-54岁|170-188cm|月薪:1.2万以上|大学本科|不要吸烟|是否想要孩子:以后...
2,芯儿,北京,朝阳区,36岁,汉族,河北保定,天蝎座(10.23-11.21),大学本科,未婚,160cm,45kg,苗条,传媒/艺术,5001-8000元,不吸烟,稍微喝一点酒,租房,未买车,没有小孩,31-45岁,不明,8千以上,31-45岁|工作地:北京朝阳区|月薪:8千以上|未婚
3,沁心夜雨,北京,朝阳区,49岁,汉族,河北保定,魔羯座(12.22-01.19),高中及以下,离异,168cm,58kg,苗条,自由职业,5001-8000元,不吸烟,不喝酒,已购房,未买车,有孩子且住在一起,46-53岁,170-180cm,8千以上,46-53岁|170-180cm|工作地:北京朝阳区|月薪:8千以上|离异|体型:运动员型|...
4,冰心,北京,石景山区,48岁,汉族,黑龙江牡丹江,射手座(11.22-12.21),高中及以下,离异,160cm,不明,不明,高中及以下,3001-5000元,不吸烟,不喝酒,和家人同住,未买车,有孩子但不在身边,39-54岁,不明,5千以上,39-54岁|月薪:5千以上
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4365,Miya,珠海,香洲区,35岁,汉族,重庆,魔羯座(12.22-01.19),高中及以下,离异,156cm,47kg,一般,服务业,12001-20000元,稍微抽一点烟,稍微喝一点酒,租房,未买车,有孩子但不在身边,40-47岁,170-178cm,2万以上,40-47岁|170-178cm|工作地:广东珠海|月薪:2万以上|体型:一般|不要喝酒|有...
4366,薰薰,珠海,香洲区,36岁,汉族,不明,魔羯座(12.22-01.19),高中及以下,离异,166cm,不明,不明,其他职业,12001-20000元,不吸烟,不明,不明,不明,没有小孩,31-45岁,172-182cm,2万以上,31-45岁|172-182cm|月薪:2万以上
4367,淡然,珠海,香洲区,35岁,汉族,广东珠海,天秤座(09.23-10.22),中专,未婚,160cm,48kg,瘦长,房地产交易,20001-50000元,不吸烟,社交场合会喝酒,已购房,已买车,不明,33-43岁,170-180cm,不明,33-43岁|170-180cm|工作地:广东珠海香洲区|未婚
4368,云宝贝,珠海,香洲区,28岁,汉族,广东梅州,天秤座(09.23-10.22),大学本科,离异,163cm,53kg,一般,心理医生,5001-8000元,不吸烟,稍微喝一点酒,住在单位宿舍,未买车,没有小孩,29-35岁,170-185cm,1.2万以上,29-35岁|170-185cm|工作地:广东珠海|月薪:1.2万以上|大学本科|不要喝酒|...
4369,Mask,珠海,香洲区,54岁,汉族,北京,魔羯座(12.22-01.19),大专,未婚,165cm,52kg,保密,其他职业,20001-50000元,不明,稍微喝一点酒,已购房,已买车,没有小孩,49-63岁,不明,5万以上,49-63岁|工作地:广东珠海香洲区|月薪:5万以上|未婚

## 导出数据为 珍爱网3.csv 不要行索引

In [82]:
df.to_csv('珍爱网3.csv', index=False)